import React from 'react';
import styled, { keyframes } from 'styled-components';
import payout from "../images/payouts.png";
import loud from "../images/Loud.webp";

const glow = keyframes`
  0% {
    box-shadow: 0 0 10px rgba(255, 255, 255, 0.8);
  }
  100% {
    box-shadow: 0 0 10px rgba(255, 255, 255, 1);
  }
`;

const EarnMoneyMainDiv = styled.div`
  width: 100%;
  margin-top: 10rem;
`;

const EarnMoneySecondMainDiv = styled.div`
  width: 50%;
  margin: auto;
`;

const EarnMoneyMainDivImageHolder = styled.div`
  width: 50%;
  margin: auto;
`;

const EarnMoneyMainDivImage = styled.img`
  width: 60%;
`;

const EarnMoneyThirdMainDiv = styled.div`
  width: 100%;
  color: white;
  margin: auto;
  display: flex;
  justify-content: center;
  text-align: center;
`;

const EarnMoneyThirdMainDivSpan = styled.span`
  font-family: Arial, Helvetica, sans-serif;
  font-size: 72px;
  font-weight: 700;
  letter-spacing: -2.1px;
  text-align: center;
  color: rgb(235, 255, 37);
`;

const EarnMoneyThirdMainDivPara = styled.p`
  color: rgb(255, 255, 255);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 72px;
  font-weight: 700;
  letter-spacing: -2.1px;
  text-align: center;
`;

const EarnMoneyThirdMainDivSmallPara = styled.p`
  font-family: Arial, Helvetica, sans-serif;
  font-size: 24px;
  text-align: center;
  color: rgb(231, 231, 234);
  position: relative;
  bottom: 2rem;
`;

const EarnMoneyFourthMainDiv = styled.div`
  width: 75%;
  margin: auto;
`;

const EarnMoneyFourthMainDivImageHolder = styled.div`
  width: 100%;
`;

const EarnMoneyFourthMainDivImage = styled.img`
  width: 100%;
`;

const ButtonContainer = styled.div`
  display: flex;
  margin-top: 4rem;
  justify-content: center;
`;

const AnchDivMain = styled.div`
  display: flex;
`;

const AnchButton = styled.a`
  backdrop-filter: blur(5px);
  background: linear-gradient(85.8452deg, rgb(212, 249, 56) 29.1667%, rgb(50, 216, 117) 100%);
  opacity: 1;
  padding: 0px 40px 0px 40px;
  transition: background 0.3s;
  border-radius: 8px;
  box-shadow: none;
  display: flex;
  align-items: center;
  text-decoration: none;
  color: #fff;
  font-weight: 1000;
  font-family: Arial, Helvetica, sans-serif;
  text-transform: uppercase;
  white-space: nowrap;
  animation: ${glow} 1s infinite alternate;
  &:hover {
    cursor: pointer;
  }
`;

const AnchP = styled.p`
  color: black;
  font-weight: 700;
`;

const EarnMoney = () => {
  return (
    <EarnMoneyMainDiv>
      <EarnMoneySecondMainDiv>
        <EarnMoneyMainDivImageHolder>
          <EarnMoneyMainDivImage src={loud} alt='loud' />
        </EarnMoneyMainDivImageHolder>
      </EarnMoneySecondMainDiv>

      <EarnMoneyThirdMainDiv>
        <div>
          <EarnMoneyThirdMainDivPara>
            Earn Money.<EarnMoneyThirdMainDivSpan> The Easy Way.</EarnMoneyThirdMainDivSpan>
          </EarnMoneyThirdMainDivPara>
          <EarnMoneyThirdMainDivSmallPara>Best-in-class referral and rebate program. Refer a friend and you would get 70%* </EarnMoneyThirdMainDivSmallPara>
          <EarnMoneyThirdMainDivSmallPara>of fee generated by your friend and your friend would get upto 20%* of rebate on </EarnMoneyThirdMainDivSmallPara>
          <EarnMoneyThirdMainDivSmallPara>fee</EarnMoneyThirdMainDivSmallPara>
        </div>
      </EarnMoneyThirdMainDiv>

      <EarnMoneyFourthMainDiv>
        <EarnMoneyFourthMainDivImageHolder>
          <EarnMoneyFourthMainDivImage src={payout} alt='payout' />
        </EarnMoneyFourthMainDivImageHolder>
      </EarnMoneyFourthMainDiv>

      <ButtonContainer>
        <AnchDivMain>
          <AnchButton href="#">
            <div className="after-anch">
              <AnchP>Trade Now</AnchP>
            </div>
          </AnchButton>
        </AnchDivMain>
      </ButtonContainer>
    </EarnMoneyMainDiv>
  );
};

export default EarnMoney;
